"""
KFI Sales Dashboard — Weekly Update Script
==========================================
Run this every Monday after uploading new Salesforce files.

USAGE:
    python update_dashboard.py activities.xls opportunities.xls

The script will regenerate src/data/dashboardData.js
Then run: npm run build  (or just push and Vercel rebuilds automatically)

REQUIREMENTS:
    pip install pandas openpyxl
    LibreOffice installed for .xls → .csv conversion
    OR export directly as .csv from Salesforce
"""

import sys, subprocess, os, json, datetime

TODAY    = datetime.date.today()
RDATE    = TODAY.strftime("%B %-d, %Y")

REPS = [
    "Jacob Hacker","Kyle Turner","Matt Olsen","Geoff Petrangelo",
    "Kent Buckingham","Vonn McQuiston","Mark Holmes","Mariano Lobos",
    "Jake Heinecke","Jack Subel"
]
GEOFF_COMBINED = ["Geoff Petrangelo","Eric Cin"]

def to_csv(filepath):
    if filepath.lower().endswith('.csv'):
        return filepath
    out_dir = os.path.dirname(os.path.abspath(filepath)) or '.'
    subprocess.run(
        ["libreoffice","--headless","--convert-to","csv","--outdir",out_dir,filepath],
        capture_output=True
    )
    csv_path = os.path.splitext(filepath)[0] + '.csv'
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Could not convert {filepath}")
    return csv_path

def process(act_file, opp_file):
    import pandas as pd
    act = pd.read_csv(to_csv(act_file))
    opp = pd.read_csv(to_csv(opp_file))
    act['Date'] = pd.to_datetime(act['Date'], errors='coerce')
    opp['Amount'] = opp['Amount'].fillna(0)

    result = {}
    for rep in REPS:
        acts = act[act['Assigned'].isin(GEOFF_COMBINED if rep=="Geoff Petrangelo" else [rep])].copy()
        opps = opp[opp['Opportunity Owner']==rep].copy()
        last = acts['Date'].max()
        days = int((TODAY - last.date()).days) if pd.notna(last) else 999
        pipe = float(opps['Amount'].sum())
        accts = acts['Company / Account'].dropna().unique().tolist()
        monthly = {str(m): int(len(acts[acts['Date'].dt.month==m])) for m in range(1,13)}

        opps_list = []
        for _,row in opps.sort_values('Amount',ascending=False).head(10).iterrows():
            opps_list.append({
                "name":    str(row.get('Opportunity Name',''))[:55],
                "account": str(row.get('Account Name',''))[:38],
                "stage":   str(row.get('Stage','')),
                "amount":  float(row['Amount']),
                "prob":    float(row['Probability (%)']) if pd.notna(row.get('Probability (%)')) else 0,
                "created": str(pd.to_datetime(row['Created Date']).date()) if pd.notna(row.get('Created Date')) else "",
            })

        acts_list = []
        for _,row in acts.sort_values('Date',ascending=False).head(12).iterrows():
            dt = row['Date']
            acts_list.append({
                "date":    str(dt.date()) if pd.notna(dt) else "",
                "company": str(row.get('Company / Account','')),
                "subject": str(row.get('Subject',''))[:65],
                "days_ago": int((TODAY-dt.date()).days) if pd.notna(dt) else 999,
            })

        result[rep] = {
            "n_acts": len(acts), "n_opps": len(opps),
            "pipe": pipe, "n_accts": len(accts), "accts": accts,
            "days_since": days,
            "last_act": str(last.date()) if pd.notna(last) else None,
            "monthly": monthly,
            "opps": opps_list,
            "recent_acts": acts_list,
            "conv": round(len(opps)/max(len(accts),1)*100,1),
        }
    return result

def write_js(data, out_path="src/data/dashboardData.js"):
    content = f"""// ─── KFI DASHBOARD DATA ─────────────────────────────────────────
// Auto-generated by update_dashboard.py on {TODAY}
// Do not edit manually — run the script with new Salesforce exports.

export const REPORT_DATE = {json.dumps(RDATE)};

export const REPS = {json.dumps(REPS, indent=2)};

export const REP_DATA = {json.dumps(data, indent=2)};

// FINDINGS and CHANGES are edited manually in this file after each run:
export const FINDINGS = [];  // TODO: update each week

export const CHANGES = [];   // TODO: update each week
"""
    with open(out_path,'w') as f:
        f.write(content)
    print(f"✅ {out_path} updated — {RDATE}")
    print("Next steps:")
    print("  1. Edit FINDINGS and CHANGES arrays in dashboardData.js")
    print("  2. git add . && git commit -m 'Dashboard update {RDATE}' && git push")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python update_dashboard.py <activities> <opportunities>")
        sys.exit(1)
    data = process(sys.argv[1], sys.argv[2])
    write_js(data)
